/**
 * Known tracker / analytics domains (suffix match: host === suffix || host.endsWith("." + suffix)).
 * Sorted longest-first at init for correct specificity.
 */
(function initTrackerCatalog() {
  const RAW = [
    { suffix: "googletagmanager.com", category: "tag manager", label: "Google Tag Manager" },
    { suffix: "google-analytics.com", category: "analytics", label: "Google Analytics" },
    { suffix: "googleadservices.com", category: "ad network", label: "Google Ads" },
    { suffix: "googlesyndication.com", category: "ad network", label: "Google Syndication" },
    { suffix: "doubleclick.net", category: "ad network", label: "DoubleClick" },
    { suffix: "googleads.g.doubleclick.net", category: "ad network", label: "Google Ads (DoubleClick)" },
    { suffix: "pagead2.googlesyndication.com", category: "ad network", label: "Google Page Ads" },
    { suffix: "adservice.google.com", category: "ad network", label: "Google Ad Service" },
    { suffix: "fundingchoicesmessages.google.com", category: "ad network", label: "Google Funding Choices" },
    { suffix: "analytics.google.com", category: "analytics", label: "Google Analytics 4" },
    { suffix: "region1.google-analytics.com", category: "analytics", label: "Google Analytics" },
    { suffix: "ssl.google-analytics.com", category: "analytics", label: "Google Analytics" },
    { suffix: "facebook.net", category: "social tracker", label: "Meta / Facebook" },
    { suffix: "facebook.com", category: "social tracker", label: "Facebook" },
    { suffix: "connect.facebook.net", category: "social tracker", label: "Facebook Connect" },
    { suffix: "graph.facebook.com", category: "social tracker", label: "Facebook Graph API" },
    { suffix: "pixel.facebook.com", category: "social tracker", label: "Facebook Pixel" },
    { suffix: "hotjar.com", category: "session recording", label: "Hotjar" },
    { suffix: "hotjar.io", category: "session recording", label: "Hotjar" },
    { suffix: "mouseflow.com", category: "session recording", label: "Mouseflow" },
    { suffix: "fullstory.com", category: "session recording", label: "FullStory" },
    { suffix: "logrocket.com", category: "session recording", label: "LogRocket" },
    { suffix: "logrocket.io", category: "session recording", label: "LogRocket" },
    { suffix: "clarity.ms", category: "session recording", label: "Microsoft Clarity" },
    { suffix: "crazyegg.com", category: "session recording", label: "Crazy Egg" },
    { suffix: "inspectlet.com", category: "session recording", label: "Inspectlet" },
    { suffix: "fingerprintjs.com", category: "fingerprinting", label: "FingerprintJS" },
    { suffix: "fpjs.io", category: "fingerprinting", label: "FingerprintJS" },
    { suffix: "criteo.com", category: "retargeting", label: "Criteo" },
    { suffix: "criteo.net", category: "retargeting", label: "Criteo" },
    { suffix: "taboola.com", category: "ad network", label: "Taboola" },
    { suffix: "taboolasyndication.com", category: "ad network", label: "Taboola" },
    { suffix: "outbrain.com", category: "ad network", label: "Outbrain" },
    { suffix: "scorecardresearch.com", category: "analytics", label: "Scorecard Research" },
    { suffix: "quantserve.com", category: "ad network", label: "Quantcast" },
    { suffix: "quantcast.com", category: "ad network", label: "Quantcast" },
    { suffix: "adsafeprotected.com", category: "ad network", label: "IAS / Adsafe" },
    { suffix: "moatads.com", category: "ad network", label: "Moat" },
    { suffix: "amazon-adsystem.com", category: "ad network", label: "Amazon Ads" },
    { suffix: "advertising.com", category: "ad network", label: "Verizon Media Ads" },
    { suffix: "adnxs.com", category: "ad network", label: "Xandr / AppNexus" },
    { suffix: "casalemedia.com", category: "ad network", label: "Index Exchange" },
    { suffix: "rubiconproject.com", category: "ad network", label: "Magnite / Rubicon" },
    { suffix: "pubmatic.com", category: "ad network", label: "PubMatic" },
    { suffix: "openx.net", category: "ad network", label: "OpenX" },
    { suffix: "3lift.com", category: "ad network", label: "TripleLift" },
    { suffix: "sharethrough.com", category: "ad network", label: "Sharethrough" },
    { suffix: "contextweb.com", category: "ad network", label: "ContextWeb" },
    { suffix: "bluekai.com", category: "retargeting", label: "Oracle BlueKai" },
    { suffix: "demdex.net", category: "retargeting", label: "Adobe Audience Manager" },
    { suffix: "omtrdc.net", category: "analytics", label: "Adobe Analytics" },
    { suffix: "adobe.com", category: "analytics", label: "Adobe" },
    { suffix: "segment.com", category: "analytics", label: "Segment" },
    { suffix: "segment.io", category: "analytics", label: "Segment" },
    { suffix: "mixpanel.com", category: "analytics", label: "Mixpanel" },
    { suffix: "amplitude.com", category: "analytics", label: "Amplitude" },
    { suffix: "heapanalytics.com", category: "analytics", label: "Heap" },
    { suffix: "plausible.io", category: "analytics", label: "Plausible" },
    { suffix: "matomo.cloud", category: "analytics", label: "Matomo" },
    { suffix: "cdn.optimizely.com", category: "analytics", label: "Optimizely" },
    { suffix: "optimizely.com", category: "analytics", label: "Optimizely" },
    { suffix: "licdn.com", category: "social tracker", label: "LinkedIn" },
    { suffix: "linkedin.com", category: "social tracker", label: "LinkedIn" },
    { suffix: "ads-twitter.com", category: "social tracker", label: "Twitter / X Ads" },
    { suffix: "analytics.twitter.com", category: "social tracker", label: "Twitter Analytics" },
    { suffix: "t.co", category: "social tracker", label: "Twitter short links" },
    { suffix: "snapchat.com", category: "social tracker", label: "Snapchat" },
    { suffix: "sc-static.net", category: "social tracker", label: "Snapchat" },
    { suffix: "tiktok.com", category: "social tracker", label: "TikTok" },
    { suffix: "pinterest.com", category: "social tracker", label: "Pinterest" },
    { suffix: "pinimg.com", category: "social tracker", label: "Pinterest" },
    { suffix: "reddit.com", category: "social tracker", label: "Reddit" },
    { suffix: "redditmedia.com", category: "social tracker", label: "Reddit" },
    { suffix: "bing.com", category: "ad network", label: "Microsoft Bing Ads" },
    { suffix: "bat.bing.com", category: "ad network", label: "Bing UET" },
    { suffix: "yimg.com", category: "ad network", label: "Yahoo" },
    { suffix: "yahoo.com", category: "ad network", label: "Yahoo" },
    { suffix: "adsrvr.org", category: "ad network", label: "The Trade Desk" },
    { suffix: "360yield.com", category: "ad network", label: "Ad yield" },
    { suffix: "adform.net", category: "ad network", label: "Adform" },
    { suffix: "smaato.net", category: "ad network", label: "Smaato" },
    { suffix: "inmobi.com", category: "ad network", label: "InMobi" },
    { suffix: "tapad.com", category: "ad network", label: "Tapad" },
    { suffix: "liveramp.com", category: "retargeting", label: "LiveRamp" },
    { suffix: "rlcdn.com", category: "retargeting", label: "LiveRamp" },
    { suffix: "krxd.net", category: "retargeting", label: "Salesforce Krux" },
    { suffix: "salesforceliveagent.com", category: "analytics", label: "Salesforce" },
    { suffix: "hubspot.com", category: "analytics", label: "HubSpot" },
    { suffix: "hs-scripts.com", category: "analytics", label: "HubSpot" },
    { suffix: "hs-analytics.net", category: "analytics", label: "HubSpot" },
    { suffix: "hs-banner.com", category: "analytics", label: "HubSpot" },
    { suffix: "intercom.io", category: "analytics", label: "Intercom" },
    { suffix: "intercomcdn.com", category: "analytics", label: "Intercom" },
    { suffix: "zendesk.com", category: "analytics", label: "Zendesk" },
    { suffix: "zdassets.com", category: "analytics", label: "Zendesk" },
    { suffix: "driftt.com", category: "analytics", label: "Drift" },
    { suffix: "pardot.com", category: "analytics", label: "Pardot" },
    { suffix: "marketo.net", category: "analytics", label: "Marketo" },
    { suffix: "mktoresp.com", category: "analytics", label: "Marketo" },
    { suffix: "newrelic.com", category: "analytics", label: "New Relic" },
    { suffix: "nr-data.net", category: "analytics", label: "New Relic" },
    { suffix: "datadoghq.com", category: "analytics", label: "Datadog" },
    { suffix: "browser-intake-datadoghq.com", category: "analytics", label: "Datadog" },
    { suffix: "sentry.io", category: "analytics", label: "Sentry" },
    { suffix: "ingest.sentry.io", category: "analytics", label: "Sentry" },
    { suffix: "bugsnag.com", category: "analytics", label: "Bugsnag" },
    { suffix: "rollbar.com", category: "analytics", label: "Rollbar" },
    { suffix: "branch.io", category: "analytics", label: "Branch" },
    { suffix: "app.link", category: "analytics", label: "Branch" },
    { suffix: "adjust.com", category: "analytics", label: "Adjust" },
    { suffix: "appsflyer.com", category: "analytics", label: "AppsFlyer" },
    { suffix: "firebaseio.com", category: "analytics", label: "Firebase" },
    { suffix: "cloudflareinsights.com", category: "analytics", label: "Cloudflare Web Analytics" },
    { suffix: "vimeo.com", category: "social tracker", label: "Vimeo" },
    { suffix: "youtube.com", category: "social tracker", label: "YouTube" },
    { suffix: "adsymptotic.com", category: "ad network", label: "Adsymptotic" },
    { suffix: "adroll.com", category: "retargeting", label: "AdRoll" },
    { suffix: "d.adroll.com", category: "retargeting", label: "AdRoll" },
    { suffix: "bounceexchange.com", category: "ad network", label: "BounceX" },
    { suffix: "onetrust.com", category: "analytics", label: "OneTrust CMP" },
    { suffix: "cookielaw.org", category: "analytics", label: "CookiePro / OneTrust" },
    { suffix: "cookiebot.com", category: "analytics", label: "Cookiebot" },
    { suffix: "trustarc.com", category: "analytics", label: "TrustArc" },
    { suffix: "iubenda.com", category: "analytics", label: "iubenda" },
    { suffix: "chartbeat.com", category: "analytics", label: "Chartbeat" },
    { suffix: "parsely.com", category: "analytics", label: "Parse.ly" },
    { suffix: "mparticle.com", category: "analytics", label: "mParticle" },
    { suffix: "braze.com", category: "analytics", label: "Braze" },
    { suffix: "customer.io", category: "analytics", label: "Customer.io" },
    { suffix: "klaviyo.com", category: "analytics", label: "Klaviyo" },
    { suffix: "mailchimp.com", category: "analytics", label: "Mailchimp" },
    { suffix: "list-manage.com", category: "analytics", label: "Mailchimp" },
    { suffix: "sendgrid.net", category: "analytics", label: "SendGrid" },
    { suffix: "stripe.com", category: "analytics", label: "Stripe" },
    { suffix: "m.stripe.network", category: "analytics", label: "Stripe" },
  ];

  self.PC_TRACKER_RULES = RAW.sort((a, b) => b.suffix.length - a.suffix.length);

  /**
   * @param {string} hostname
   * @returns {{ suffix: string, category: string, label: string } | null}
   */
  self.pcClassifyTrackerHost = function pcClassifyTrackerHost(hostname) {
    if (!hostname || typeof hostname !== "string") return null;
    const h = hostname.toLowerCase();
    for (let i = 0; i < self.PC_TRACKER_RULES.length; i++) {
      const rule = self.PC_TRACKER_RULES[i];
      const s = rule.suffix;
      if (h === s || (h.length > s.length && h.endsWith("." + s))) {
        return { suffix: s, category: rule.category, label: rule.label };
      }
    }
    return null;
  };
})();
